### ISSUE TITLE
some quetion

### ISSUE THREAD

**Issue by huguilei** [TadasBaltrusaitis/CCNF#3]
data_preparation:when i use your code to prepare data for wild, i find your code uses a pre-trained data--pdm_68_aligned_wild.mat in the PDM_helpers.So how can I make a mat-flie for my data?thank you for your help.

**Comment by TadasBaltrusaitis** [comment]
To create a point distribution model yourself have a look at - https://github.com/TadasBaltrusaitis/OpenFace/tree/master/matlab_version/pdm_generation

**Comment by huguilei** [comment]
thank you for your help!
