### ISSUE TITLE
how to calculate the  partial derivatives?

### ISSUE THREAD

**Issue by Veridium2019** [TadasBaltrusaitis/CCNF#4]
I am pretty interested in this work and I also read your 2013 CCRF papers. But I can't find the detailed derivation of the partial derivatives of eq7. In your paper, you mentioned it can be found in supplementary material. Do you have a link to this supplementary material? Thanks.

**Comment by TadasBaltrusaitis** [comment]
Sorry for the delay, you can find the appendix here - https://www.dropbox.com/s/1ttrwotjlc9x16j/appendix.pdf?dl=0
